name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ Development ]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: sh 1b-prep-dl2.sh
  dev:
    name: Development
    steps:
      - name: Run the developer
  corpus:
    name: Corpus
    steps:
      - name: Run the developer
        run: sh 1a-prep-dl1.sh
  test:
    needs: [ build, corpus, dev ]
    name: Testing
    steps:
      - name: Testing the application
        run: sh 2-test.sh

