name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ ]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run:
          pwd
          ls -l
          sh 1b-prep-dl2.sh
          sh 1c-prep-comp.sh
  corpus:
    name: Corpus
    runs-on: ubuntu-latest
    steps:
      - name: download corpus
        run:
          pwd
          ls -l
          sh 1a-prep-dl1.sh
  test:
    needs: [ build, corpus ]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Testing the application
        run:
          pwd
          ls -l
          sh 2-test.sh
